#!/usr/bin/env python3
"""Локальное создание keystore и android/key.properties для release-APK.

Без подписи `flutter build apk --release` выпускает неподписанный APK,
который Android отказывается устанавливать. Этот скрипт создаёт личный
keystore локальным `keytool` из установленной JDK и заполняет
`android/key.properties` в формате, который уже читает
`android/app/build.gradle.kts`.

Правила безопасности:

- ничего не скачивается и не выгружается, сеть не используется;
- пароль не печатается, не логируется и не передаётся в аргументах
  процесса (только через stdin `keytool`);
- существующие keystore и `android/key.properties` никогда не
  перезаписываются: повторный запуск безопасен и просто сообщает, что
  подпись уже настроена;
- при любой ошибке частичные файлы удаляются, прежнее состояние остаётся.
"""
from __future__ import annotations

import argparse
import os
import secrets
import shutil
import string
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Sequence

DEFAULT_ALIAS = "upload"
DEFAULT_KEYSTORE_NAME = "upload-keystore.jks"
DEFAULT_VALIDITY_DAYS = 10000
DEFAULT_KEY_SIZE = 2048
DEFAULT_DNAME = "CN=AI Workbench, OU=Personal, O=AI Workbench, C=KZ"
PASSWORD_ALPHABET = string.ascii_letters + string.digits
PASSWORD_LENGTH = 28
KEYTOOL_TIMEOUT_SECONDS = 300.0

REQUIRED_SIGNING_KEYS = ("storePassword", "keyPassword", "keyAlias", "storeFile")


class KeystoreFailure(RuntimeError):
    """Понятная пользователю ошибка без секретов в тексте."""


# --------------------------------------------------------------------------
# java.util.Properties safe writing
# --------------------------------------------------------------------------

_KEY_SPECIALS = "=: \t\f#!"


def _escape_common(value: str) -> str:
    result: list[str] = []
    for char in value:
        if char == "\\":
            result.append("\\\\")
        elif char == "\n":
            result.append("\\n")
        elif char == "\r":
            result.append("\\r")
        elif char == "\t":
            result.append("\\t")
        elif char == "\f":
            result.append("\\f")
        elif ord(char) > 0xFF:
            # Gradle читает key.properties как ISO-8859-1, поэтому всё вне
            # latin-1 (например, кириллица в пути Windows) кодируется
            # java unicode escape.
            encoded = char.encode("utf-16-be")
            for index in range(0, len(encoded), 2):
                code = (encoded[index] << 8) | encoded[index + 1]
                result.append(f"\\u{code:04x}")
        else:
            result.append(char)
    return "".join(result)


def escape_property_key(key: str) -> str:
    escaped = _escape_common(key)
    out: list[str] = []
    for char in escaped:
        if char in _KEY_SPECIALS:
            out.append("\\" + char)
        else:
            out.append(char)
    return "".join(out)


def escape_property_value(value: str) -> str:
    escaped = _escape_common(value)
    # Ведущие пробелы в значении Properties проглатывает, поэтому первый
    # пробел экранируется. Остальные пробелы значимы и остаются как есть.
    if escaped.startswith(" "):
        escaped = "\\" + escaped
    return escaped


def render_key_properties(
    *, store_password: str, key_password: str, key_alias: str, store_file: str
) -> str:
    pairs = (
        ("storePassword", store_password),
        ("keyPassword", key_password),
        ("keyAlias", key_alias),
        ("storeFile", store_file),
    )
    # Файл читается Gradle как ISO-8859-1, поэтому служебные комментарии
    # внутри key.properties остаются ASCII.
    lines = [
        "# Local release signing secrets. Do not commit, share or publish.",
        "# Generated by tools/make_keystore.py. Keep it on this machine only.",
    ]
    lines.extend(
        f"{escape_property_key(key)}={escape_property_value(value)}" for key, value in pairs
    )
    return "\n".join(lines) + "\n"


def generate_password() -> str:
    # Алфавит без разделителей Properties и без спецсимволов оболочки:
    # значение остаётся однозначным и не требует экранирования.
    return "".join(secrets.choice(PASSWORD_ALPHABET) for _ in range(PASSWORD_LENGTH))


def atomic_write_secret(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, name = tempfile.mkstemp(prefix=".key-", suffix=".tmp", dir=path.parent)
    temporary = Path(name)
    try:
        with os.fdopen(handle, "w", encoding="latin-1", newline="\n") as target:
            target.write(text)
            target.flush()
            os.fsync(target.fileno())
        try:
            os.chmod(temporary, 0o600)
        except OSError:
            # Windows и часть сетевых ФС не поддерживают POSIX-режимы.
            pass
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            try:
                temporary.unlink()
            except OSError:
                pass


# --------------------------------------------------------------------------
# keytool
# --------------------------------------------------------------------------


def _keytool_names() -> tuple[str, ...]:
    return ("keytool.exe", "keytool") if os.name == "nt" else ("keytool",)


def find_keytool(requested: str | None = None, *, env: dict[str, str] | None = None) -> str:
    environment = os.environ if env is None else env
    if requested:
        candidate = Path(requested).expanduser()
        if candidate.is_file():
            return str(candidate.resolve())
        found = shutil.which(requested)
        if found:
            return found
        raise KeystoreFailure(f"Не найден keytool по указанному пути: {requested}")
    for variable in ("JAVA_HOME", "JDK_HOME"):
        home = environment.get(variable)
        if not home:
            continue
        for name in _keytool_names():
            candidate = Path(home).expanduser() / "bin" / name
            if candidate.is_file():
                return str(candidate.resolve())
    for name in _keytool_names():
        found = shutil.which(name)
        if found:
            return found
    raise KeystoreFailure(
        "Не найден keytool. Установите JDK 17+ (она нужна и для сборки "
        "Android) или укажите путь: --keytool-bin /path/to/keytool"
    )


def _redact(text: str, secret: str) -> str:
    return text.replace(secret, "[скрыто]") if secret else text


def run_keytool(
    keytool: str,
    arguments: Sequence[str],
    *,
    stdin_text: str,
    secret: str,
    timeout: float = KEYTOOL_TIMEOUT_SECONDS,
) -> str:
    command = [keytool, *arguments]
    try:
        finished = subprocess.run(
            command,
            input=stdin_text,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
            check=False,
        )
    except OSError as error:
        raise KeystoreFailure(f"Не удалось запустить keytool: {error}") from error
    except subprocess.TimeoutExpired as error:
        raise KeystoreFailure("keytool не ответил в отведённое время.") from error
    output = _redact((finished.stdout or "") + (finished.stderr or ""), secret)
    if finished.returncode != 0:
        tail = "\n".join(output.strip().splitlines()[-8:])
        raise KeystoreFailure(
            "keytool завершился с кодом "
            f"{finished.returncode}. Вывод (без секретов):\n{tail}"
        )
    return output


# --------------------------------------------------------------------------
# main flow
# --------------------------------------------------------------------------


def resolve_keystore_path(root: Path, raw: str | None) -> tuple[Path, str]:
    """Возвращает (абсолютный путь keystore, значение storeFile).

    Значение storeFile интерпретируется Gradle через `file()` внутри
    проекта `android/app`, поэтому относительный путь по умолчанию
    указывает именно туда.
    """
    app_dir = root / "android" / "app"
    if raw is None:
        return app_dir / DEFAULT_KEYSTORE_NAME, DEFAULT_KEYSTORE_NAME
    candidate = Path(raw).expanduser()
    if candidate.is_absolute():
        return candidate, str(candidate)
    resolved = (app_dir / candidate).resolve()
    return resolved, str(candidate).replace(os.sep, "/")


def existing_signing_state(root: Path) -> tuple[Path, bool]:
    properties_path = root / "android" / "key.properties"
    return properties_path, properties_path.is_file()


def create_keystore(
    *,
    root: Path,
    keytool: str,
    keystore_path: Path,
    store_file_value: str,
    alias: str,
    validity_days: int,
    key_size: int,
    dname: str,
    password: str,
) -> None:
    keystore_path.parent.mkdir(parents=True, exist_ok=True)
    created_keystore = False
    try:
        run_keytool(
            keytool,
            [
                "-genkeypair",
                "-alias", alias,
                "-keyalg", "RSA",
                "-keysize", str(key_size),
                "-validity", str(validity_days),
                "-keystore", str(keystore_path),
                "-dname", dname,
            ],
            # keytool спрашивает пароль хранилища дважды, затем предлагает
            # оставить пароль ключа таким же (пустая строка = «как у
            # хранилища»). Пароль идёт только через stdin.
            stdin_text=f"{password}\n{password}\n\n",
            secret=password,
        )
        created_keystore = keystore_path.is_file()
        if not created_keystore:
            raise KeystoreFailure("keytool не создал файл keystore.")
        try:
            os.chmod(keystore_path, 0o600)
        except OSError:
            pass
        run_keytool(
            keytool,
            ["-list", "-alias", alias, "-keystore", str(keystore_path)],
            stdin_text=f"{password}\n",
            secret=password,
        )
        atomic_write_secret(
            root / "android" / "key.properties",
            render_key_properties(
                store_password=password,
                key_password=password,
                key_alias=alias,
                store_file=store_file_value,
            ),
        )
    except BaseException:
        # Частичный результат не оставляем: иначе следующий запуск решит,
        # что подпись уже настроена.
        if created_keystore:
            try:
                keystore_path.unlink()
            except OSError:
                pass
        raise


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Создать личный keystore и android/key.properties для "
            "установки release-APK. Работает офлайн и не печатает пароль."
        ),
    )
    parser.add_argument("--alias", default=DEFAULT_ALIAS)
    parser.add_argument(
        "--keystore",
        help=(
            "Путь к keystore. Относительный путь считается от android/app, "
            f"по умолчанию {DEFAULT_KEYSTORE_NAME}."
        ),
    )
    parser.add_argument("--validity-days", type=int, default=DEFAULT_VALIDITY_DAYS)
    parser.add_argument("--key-size", type=int, default=DEFAULT_KEY_SIZE)
    parser.add_argument("--dname", default=DEFAULT_DNAME)
    parser.add_argument(
        "--password-env",
        help=(
            "Имя переменной окружения со своим паролем. По умолчанию "
            "генерируется случайный пароль и сохраняется только в "
            "android/key.properties."
        ),
    )
    parser.add_argument("--keytool-bin", help="Путь к keytool из JDK")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Показать план без запуска keytool и без изменения файлов.",
    )
    parser.add_argument("--project-root", help=argparse.SUPPRESS)
    return parser.parse_args(argv)


def run(argv: Sequence[str]) -> int:
    options = parse_args(argv)
    default_root = Path(__file__).resolve().parents[1]
    root = Path(options.project_root).resolve() if options.project_root else default_root
    if not (root / "pubspec.yaml").is_file():
        raise KeystoreFailure(f"Не найден pubspec.yaml: {root}")
    if options.validity_days < 365:
        raise KeystoreFailure("--validity-days должен быть не меньше 365.")
    if options.key_size < 2048:
        raise KeystoreFailure("--key-size должен быть не меньше 2048.")
    if not options.alias.strip():
        raise KeystoreFailure("--alias не может быть пустым.")

    properties_path, properties_exists = existing_signing_state(root)
    keystore_path, store_file_value = resolve_keystore_path(root, options.keystore)

    if properties_exists:
        print("Подпись release уже настроена: android/key.properties существует.")
        print("Файл не изменён. Чтобы пересоздать ключ, сначала сохраните копию")
        print("и удалите android/key.properties вручную.")
        print("Важно: обновление поверх уже установленного APK работает только")
        print("с тем же keystore.")
        return 0
    if keystore_path.exists():
        raise KeystoreFailure(
            "Файл keystore уже существует, а android/key.properties нет. "
            "Заполните android/key.properties вручную по образцу "
            "android/key.properties.example, чтобы не потерять прежний ключ."
        )

    if options.password_env:
        password = os.environ.get(options.password_env, "")
        if len(password) < 6:
            raise KeystoreFailure(
                f"Переменная {options.password_env} пуста или короче 6 символов."
            )
    else:
        password = generate_password()

    if options.dry_run:
        print("Dry-run: файлы не создаются, keytool не запускается.")
        print(f"keystore:   {keystore_path}")
        print(f"storeFile:  {store_file_value}")
        print(f"alias:      {options.alias}")
        print(f"срок:       {options.validity_days} дней")
        print(f"ключ:       RSA {options.key_size}")
        print(f"key.properties: {properties_path}")
        return 0

    keytool = find_keytool(options.keytool_bin)
    create_keystore(
        root=root,
        keytool=keytool,
        keystore_path=keystore_path,
        store_file_value=store_file_value,
        alias=options.alias,
        validity_days=options.validity_days,
        key_size=options.key_size,
        dname=options.dname,
        password=password,
    )

    print("Подпись release настроена.")
    print(f"keystore:       {keystore_path}")
    print(f"key.properties: {properties_path}")
    print(f"alias:          {options.alias}")
    print("Пароль сохранён только в android/key.properties и не печатается.")
    print("")
    print("Сделайте резервную копию keystore и key.properties ВНЕ проекта:")
    print("без них следующую версию нельзя установить поверх этой.")
    print("Оба файла уже исключены из Git. Никому их не пересылайте.")
    print("")
    print("Дальше: sh build_apk.sh --mode release")
    return 0


def main() -> int:
    try:
        return run(sys.argv[1:])
    except KeystoreFailure as error:
        print(f"\nОстановлено: {error}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("\nОтменено пользователем.", file=sys.stderr)
        return 130
    except OSError as error:
        print(
            "\nОстановлено: ошибка файловой системы "
            f"({type(error).__name__}). Проверьте права и свободное место.",
            file=sys.stderr,
        )
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
